1367   as a project manager, i want the existing image data to be set up in cvat ready for annotation
OpenTrafficCam/OTLabels pull request #36
Opened 2023-03-07 11:49 UTC by MichHeilig

Changelog:
* Add field "status" to stored images in database
* Automatically set state of the image (imported, pre-annoteted, in annotation) in database
* Fix bug "OP#1641 Filter out more than one label when exporting data to CVAT is not working"
* Add console outputs for anntation.py for user feedback

2023-03-15 18:23 UTC, briemla requested changes

2023-03-15 18:23 UTC, briemla commented on OTLabels/images/import_images.py
> +                    file_type = str(img).split(".")[-1]
If `img` is a `Path` object, use `img.suffix`

2023-03-15 18:23 UTC, briemla commented on OTLabels/images/import_images.py
> +                        and Path(label_path).stat().st_size > 0
If the file is empty, the resulting `DataFrame` should be empty and the loop will automatically not be processed.

2023-03-15 18:23 UTC, briemla commented on OTLabels/images/import_images.py
> +                            label = labels.loc[[i]]
Why double brackets?

2023-03-15 21:01 UTC, MichHeilig commented on OTLabels/annotate/pre_annotate.py
> +
In this function, the classes of (pre-)annotated images are filtered. `Path...st_size` is used to check if the txt-file containing the labels is empty. I thought that checking the file size instaed of performing an input of an empty file is the more convenient way to go.

2023-03-15 21:08 UTC, MichHeilig commented on OTLabels/config/training_data.json
This files contains the information (metadata/tags and file paths) of image data. I suggest changing the file name to `image_data.json`.
```suggestion
{image_data.json}
```

2023-03-15 21:21 UTC, MichHeilig commented on OTLabels/copy_image_data.py
> +    name="Heiligenstadt-Leipzig_OTCamera13",
No

2023-03-15 21:21 UTC, MichHeilig commented on OTLabels/copy_image_data.py
> +    name="Heiligenstadt-Leipzig_OTCamera15",
No

2023-03-15 21:24 UTC, MichHeilig commented on OTLabels/copy_image_data.py
> +    name="TUD_Dresden_Alaunstr_cam3",
This is another site, so no switching necessary

2023-03-15 21:24 UTC, MichHeilig commented on OTLabels/copy_image_data.py
> +    name="Heiligenstadt-Leipzig_OTCamera20",
No

2023-03-15 21:25 UTC, MichHeilig commented on OTLabels/copy_image_data.py
> +    name="Aachen_OTCamera15",
No

2023-03-15 21:25 UTC, MichHeilig commented on OTLabels/copy_image_data.py
> +    name="Aachen_OTCamera19",
No

2023-03-15 21:30 UTC, MichHeilig commented on OTLabels/copy_image_data.py
Since it is no common file structure (in this case: `path/"reviewer"`) which we import the data from, I decided not to use a json-file.

2023-03-15 21:30 UTC, MichHeilig commented on OTLabels/copy_image_data.py
> +    name="Heiligenstadt-Leipzig_OTCamera04",
No

2023-03-15 21:31 UTC, MichHeilig commented on OTLabels/copy_image_data.py
> +    name="Saarbruecken_OTCamera13",
No

2023-03-15 21:52 UTC, MichHeilig commented on OTLabels/images/copy_images.py
> +                "image_path": f"{site.output_path}/{site.name}/images",
Like this?

2023-03-15 21:56 UTC, MichHeilig commented on OTLabels/images/import_images.py
> +                        and Path(label_path).stat().st_size > 0
Wouldn't be there an error in that case?

2023-03-15 21:57 UTC, MichHeilig commented on OTLabels/images/import_images.py
> +                            label = labels.loc[[i]]
I want to get the row and that is one way to go.

2023-03-15 22:05 UTC, MichHeilig commented on OTLabels/labels/dataset.py
> +        pass
This class should was supposed to perform the import, which is now done in `import_images.py`. File can be deleted.

2023-03-15 22:07 UTC, MichHeilig commented on tests/OTLabels/annotate/test_pre_annotate.py
> +        erwartetes_ergebnis = "data/image_data/Aachen_OTCamera12/images"
Copy paste from other test scripts ;)

2023-03-20 09:50 UTC, briemla requested changes

2023-03-20 09:50 UTC, briemla commented on OTLabels/images/copy_images.py
>                  dict.fromkeys(
Why are these function definitions inside the `__init__` method?

2023-03-20 09:50 UTC, briemla commented on OTLabels/images/import_images.py
> +                        and Path(label_path).stat().st_size > 0
Ok, I had in mind that it works with empty files but at least one column is required.

2024-02-12 14:32 UTC, merged